In [ ]:
import pandas as pd

Mounted at /content/drive

In [ ]:
file_path = '../athlete_events_post_1990.csv'
athlete_data = pd.read_csv(file_path)

athlete_data.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
3,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
4,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,NaN

In [ ]:
athlete_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122216 entries, 0 to 122215
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      122216 non-null  int64
 1   Name    122216 non-null  object
 2   Sex     122216 non-null  object
 3   Age     122157 non-null  float64
 4   Height  116188 non-null  float64
 5   Weight  115753 non-null  float64
 6   Team    122216 non-null  object
 7   NOC     122216 non-null  object
 8   Games   122216 non-null  object
 9   Year    122216 non-null  int64
 10  Season  122216 non-null  object
 11  City    122216 non-null  object
 12  Sport   122216 non-null  object
 13  Event   122216 non-null  object
 14  Medal   16781 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 14.0+ MB

In [ ]:
athlete_data.describe()

,ID,Age,Height,Weight,Year
count,122216.000000,122157.000000,116188.000000,115753.000000,122216.000000
mean,68918.618454,25.471238,175.821591,71.101126,2003.854209
std,39137.352406,5.395603,10.901634,15.152324,7.889321
min,1.000000,11.000000,133.000000,28.000000,1992.000000
25%,35437.000000,22.000000,168.000000,60.000000,1996.000000
50%,69121.000000,25.000000,176.000000,70.000000,2004.000000
75%,102672.000000,28.000000,183.000000,80.000000,2012.000000
max,135571.000000,71.000000,226.000000,214.000000,2016.000000

In [ ]:
modes_df= athlete_data.mode(numeric_only=True);
modes_df

       ID   Age  Height  Weight    Year
0   94406  24.0   180.0    70.0  1992.0
1  133279   NaN     NaN     NaN     NaN

In [ ]:
athlete_data.nunique(dropna=False)

ID        61334
Name      61034
Sex           2
Age          57
Height       90
Weight      206
Team        364
NOC         213
Games        14
Year         13
Season        2
City         14
Sport        51
Event       467
Medal         4
dtype: int64

In [ ]:
athlete_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122216 entries, 0 to 122215
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      122216 non-null  int64
 1   Name    122216 non-null  object
 2   Sex     122216 non-null  object
 3   Age     122157 non-null  float64
 4   Height  116188 non-null  float64
 5   Weight  115753 non-null  float64
 6   Team    122216 non-null  object
 7   NOC     122216 non-null  object
 8   Games   122216 non-null  object
 9   Year    122216 non-null  int64
 10  Season  122216 non-null  object
 11  City    122216 non-null  object
 12  Sport   122216 non-null  object
 13  Event   122216 non-null  object
 14  Medal   16781 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 14.0+ MB

In [ ]:
athlete_data[athlete_data.duplicated(keep=False)]

Empty DataFrame
Columns: [ID, Name, Sex, Age, Height, Weight, Team, NOC, Games, Year, Season, City, Sport, Event, Medal]
Index: []

In [ ]:
athlete_data.isnull().sum()

ID             0
Name           0
Sex            0
Age           59
Height      6028
Weight      6463
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     105435
dtype: int64

In [ ]:
athlete_data.value_counts(['Age']).head()

Age
24.0    10365
23.0    10228
25.0     9673
22.0     9489
26.0     8813
Name: count, dtype: int64

In [ ]:
athlete_data.value_counts(['Sport']).head()

Sport
Athletics               16113
Swimming                11464
Gymnastics               7652
Cross Country Skiing     5165
Cycling                  4342
Name: count, dtype: int64

In [ ]:
athlete_data.query("Sport == 'Athletics'")

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
28,18,Timo Antero Aaltonen,M,31.0,189.0,130.0,Finland,FIN,2000 Summer,2000,Summer,Sydney,Athletics,Athletics Men's Shot Put,NaN
57,34,Jamale (Djamel-) Aarrass (Ahrass-),M,30.0,187.0,76.0,France,FRA,2012 Summer,2012,Summer,London,Athletics,"Athletics Men's 1,500 metres",NaN
72,49,Moonika Aava,F,24.0,168.0,65.0,Estonia,EST,2004 Summer,2004,Summer,Athina,Athletics,Athletics Women's Javelin Throw,NaN
73,49,Moonika Aava,F,28.0,168.0,65.0,Estonia,EST,2008 Summer,2008,Summer,Beijing,Athletics,Athletics Women's Javelin Throw,NaN
83,55,Antonio Abadia Beci,M,26.0,170.0,65.0,Spain,ESP,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,"Athletics Men's 5,000 metres",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122171,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,Athletics Women's 100 metres,NaN
122172,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,Athletics Women's 200 metres,NaN
122173,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,Athletics Women's 4 x 100 metres Relay,NaN
122204,135563,Olesya Nikolayevna Zykina,F,19.0,171.0,64.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Athletics,Athletics Women's 4 x 400 metres Relay,Bronze
122205,135563,Olesya Nikolayevna Zykina,F,23.0,171.0,64.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Athletics,Athletics Women's 4 x 400 metres Relay,Silver